#!/usr/bin/env bash
# Guardian shadow-window checkpoint + term-roll detector.
#
#   ./ops/guardian-checkpoint.sh            print a journal-ready entry
#   ./ops/guardian-checkpoint.sh --append   print it AND append to the journal
#
# Why this exists: the day-1/2/3 checkpoints of the shadow window were never written,
# because writing one meant an hour of ad-hoc SQL and someone remembering to do it.
# Deterministic code, not an agent and not a reminder — running it is one command.
#
# It also carries the M-10 term-roll detector. `blocked_wrong_term` is recorded by the
# Guardian and pages nobody (guardian.py:502 classifies it yellow; only RED pages), so a
# semester roll would silently strand every existing watch. Until that paging fix ships,
# THIS is the detection path. It shouts if the count is non-zero.
set -uo pipefail
VM="${SEATWATCH_VM:-ubuntu@141.148.27.134}"
KEY="${SEATWATCH_KEY:-$HOME/.ssh/seatwatch-vm.key}"
JOURNAL="$(cd "$(dirname "$0")/.." && pwd)/ORG/records/guardian-phase-d-journal.md"
WINDOW_OPEN=${WINDOW_OPEN:-1785045272}   # 2026-07-26 06:14:32Z — shadow window opened

OUT=$(ssh -i "$KEY" -o IdentitiesOnly=yes "$VM" "cd ~/seatwatch && sudo python3 - <<'PY'
import sqlite3, time, datetime, json
W = $WINDOW_OPEN
c = sqlite3.connect('file:watches.db?mode=ro', uri=True)
now = time.time()
n, mn, mx = c.execute('SELECT COUNT(*),MIN(started),MAX(started) FROM guardian_cycles WHERE started>=?', (W,)).fetchone()
if not n:
    print('NO CYCLES IN WINDOW — the poller may be down. Investigate before anything else.'); raise SystemExit
f = lambda t: datetime.datetime.utcfromtimestamp(t).strftime('%Y-%m-%d %H:%M')
print('window_open   %s' % f(W))
print('latest_cycle  %s' % f(mx))
print('elapsed_days  %.1f of 14' % ((mx - W) / 86400.0))
print('cycles        %d' % n)
st = dict(c.execute('SELECT status,COUNT(*) FROM guardian_cycles WHERE started>=? GROUP BY status', (W,)).fetchall())
print('status        %s' % json.dumps(st))
print('red_cycles    %d' % st.get('RED', 0))
inc = c.execute('SELECT kind,severity,COUNT(*) FROM guardian_incidents WHERE last_seen>=? GROUP BY kind,severity ORDER BY 3 DESC', (W,)).fetchall()
print('incidents     %s' % (json.dumps([list(r) for r in inc]) if inc else 'none'))
row = c.execute('SELECT score,tier,binding,factors FROM guardian_confidence ORDER BY rowid DESC LIMIT 1').fetchone()
if row:
    print('confidence    score=%s tier=%s binding=%s' % (row[0], row[1], row[2]))
    print('factors       %s' % row[3])
# ---- M-10 term-roll detector -------------------------------------------------
stale = c.execute(\"SELECT school, term, adapter_term, COUNT(*) FROM guardian_watch_results \"
                  \"WHERE outcome='blocked_wrong_term' AND cycle_id IN \"
                  \"(SELECT cycle_id FROM guardian_cycles ORDER BY started DESC LIMIT 100) \"
                  \"GROUP BY school, term, adapter_term\").fetchall()
if stale:
    print('TERM_ROLL_ALERT  *** %d school/term pairs have STRANDED WATCHES ***' % len(stale))
    for s, wt, at, k in stale:
        print('   %s: %d watches stamped %s, school now on %s — THESE NEVER ALERT' % (s, k, wt, at))
    print('   -> follow ops/TERM-ROLL-PROCEDURE.md. Do NOT bump the term to clear the error.')
else:
    print('term_roll     clear — no stranded watches in the last 100 cycles')
print('watch_terms   %s' % json.dumps(dict(c.execute('SELECT term,COUNT(*) FROM watches GROUP BY term').fetchall())))
PY")

STAMP=$(date -u +%Y-%m-%d)
ENTRY="
### ${STAMP} — SHADOW CHECKPOINT (generated by ops/guardian-checkpoint.sh)
\`\`\`
${OUT}
\`\`\`
Verdict: __________ (SAFE TO CONTINUE / INVESTIGATE / STOP — fill in before committing)
"

echo "$ENTRY"
if [ "${1:-}" = "--append" ]; then
  printf '%s\n' "$ENTRY" >> "$JOURNAL"
  echo ">> appended to $JOURNAL — set the verdict, then commit."
fi
if grep -q "TERM_ROLL_ALERT" <<<"$OUT"; then
  echo ""
  echo "!!! TERM ROLL DETECTED — stranded watches are NOT alerting. Act on this today. !!!"
  exit 2
fi
